### ISSUE TITLE
Support julia markdown (.jmd) files

### ISSUE THREAD

**Issue by davidanthoff** [ZacLN/CSTParser.jl#1]
I thought I'd bring this up now rather than later ;) It would be great if we could get all of this working for .jmd markdown files as used in [Weave.jl](https://github.com/mpastell/Weave.jl), i.e. if we had the full intellisense available for code blocks in weave files.

**Comment by ZacLN** [comment]
Am I right in thinking that this would just involve parsing everything inside single and triple back quotes and treating the rest as white space?

**Comment by davidanthoff** [comment]
Yes

**Comment by ZacLN** [comment]
Great, that's easy. Are there any other jmd specific features we'd want?

**Comment by davidanthoff** [comment]
Ok, I had another look. I think there really are only two types of blocks for which we simply want to enable all the LS features: 1) code blocks and 2) inline code.

Code blocks look like this:
````
```julia
println("This is julia code")
```
````
They can also have additional config options, see [here](http://weavejl.mpastell.com/latest/usage/#markdown-format).
[Inline code](http://weavejl.mpastell.com/latest/usage/#inline-code) starts with
````
This is some markdown `j log(2)` with inline julia code.
````
So I guess we should actually only activate the LS for julia code blocks, not for everything that is in back quotes, right?

Weave supports a whole bunch of other formats as well, but I almost feel we should just support one and be done... And markdown seems the most useful?

**Comment by ZacLN** [comment]
Yep, I'll check for block type before parsing

Just jmd seems good for now but if other formats also use ``` or something similar to denote blocks adding them shouldn't be a problem

**Comment by ZacLN** [comment]
[branch](https://github.com/ZacLN/Parser.jl/tree/jmd) for reference
