### ISSUE TITLE
Getting hundreds of "Possible use of undeclared variable" errors

### ISSUE THREAD

**Issue by sbromberger** [ZacLN/CSTParser.jl#18]
I can't come up with a MWE, but this is all over my lightgraphs code:

```
file: 'file:///Users/bromberger1/dev/julia/LightGraphs/src/graphtypes/simplegraphs/simpleedge.jl'
severity: 'Warning'
message: 'Possible use of undeclared variable SimpleEdge'
at: '11,1'
source: 'CSTParser.Diagnostics.Diagnostic'
```

However, this variable is indeed defined right above:
```
abstract type AbstractSimpleEdge <: AbstractEdge end

struct SimpleEdge{T<:Integer} <: AbstractSimpleEdge
    src::T
    dst::T
end

SimpleEdge(t::Tuple) = SimpleEdge(t[1], t[2]). # this is line 11
```

**Comment by ZacLN** [comment]
Hi, it seems to be missing the declaration because of the nested modules . Should be a quick fix but I'm just about to jump on a plane so it'll have to wait a day or two.

**Comment by sbromberger** [comment]
No worries - safe travels, and thanks for your talk at JuliaCon! It's what persuaded me to give VSCode a try with Julia.

**Comment by ZacLN** [comment]
Good stuff!
fixed [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/92), we'll release a v0.6.1 in a day or two

**Comment by sbromberger** [comment]
Cool! Just fyi -
```
file: 'file:///Users/seth/dev/julia/wip/LightGraphs.jl/src/community/cliques.jl'
severity: 'Warning'
message: 'Possible use of undeclared variable @traitfn'
at: '26,1'
source: 'CSTParser.Diagnostics.Diagnostic'
```

`@traitfn` is an import from `SimpleTraits.jl`.

**Comment by ZacLN** [comment]
This is fixed on 0.6.2

**Comment by sbromberger** [comment]
Actually, I don't think it is:

<img width="505" alt="screen shot 2017-07-06 at 07 48 03" src="https://user-images.githubusercontent.com/941359/27917431-d1395624-6220-11e7-9b7f-f240d812c9cc.png">

<img width="838" alt="screen shot 2017-07-06 at 07 57 05" src="https://user-images.githubusercontent.com/941359/27917448-d990bcae-6220-11e7-8e75-2fe58cf7096e.png">

<img width="478" alt="screen shot 2017-07-06 at 07 58 02" src="https://user-images.githubusercontent.com/941359/27917474-e8879a0c-6220-11e7-863d-5cc72055cce8.png">

**Comment by ZacLN** [comment]
Which package is this?

**Comment by sbromberger** [comment]
It's some unreleased code I'm developing.

**Comment by ZacLN** [comment]
Ah OK. I can't replicate the MWE (fixed by [this](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/108)). I'm going to take a bit of time trawl through packages for false positive errors so I should hit on what's causing this

**Comment by sbromberger** [comment]
Yeah, the original MWE appears to be fixed. Sorry if I'm lumping unrelated problems into the same bucket.

**Comment by ZacLN** [comment]
No no not at all, the more reported issues the better. For ref all the linting is taking place in [LanguageServer](https://github.com/JuliaEditorSupport/LanguageServer.jl/) so open new issues there
