### ISSUE TITLE
Misleading linter warning?

### ISSUE THREAD

**Issue by sbromberger** [ZacLN/CSTParser.jl#19]
```
file: 'file:///Users/seth/dev/julia/wip/LightGraphs.jl/src/community/cliques.jl'
severity: ''
message: 'ExtraWS'
at: '56,32'
source: 'CSTParser.Diagnostics.Diagnostic'
```

line in question:
```
stack = Vector{Tuple{Set{T}, Set{T}, Set{T}}}()
```

I think we should have whitespace following the commas in the tuple, no?

**Comment by ZacLN** [comment]
Thats a DataType not a tuple though?

**Comment by sbromberger** [comment]
Yep, you're right, but does that change anything? What's the lint recommendation? This:
```
stack = Vector{Tuple{Set{T},Set{T},Set{T}}}()
```
is, IMO, harder to read.

**Comment by ZacLN** [comment]
I agree but changed it to meet the conventional use in `Base`.

**Comment by sbromberger** [comment]
ah, ok, thanks.
