### ISSUE TITLE
Splitting out the formatter in a separate package? 

### ISSUE THREAD

**Issue by KristofferC** [ZacLN/CSTParser.jl#20]
Perhaps it would be worthwhile, if possible, to split it the formatter to a separate package?  This might make it easier for people to contribute to it, since it would be a smaller more focused package.

**Comment by ZacLN** [comment]
I'm trying to move all the linting/formatting to LanguageServer, I've just got to check relative speeds of the split before committing to the split.

**Comment by KristofferC** [comment]
Okay, make sense although a JuliaFormatter.jl with a simple file in, formatted file out interface would be very nice in my opinion. Perhaps that functionality could be exposed from LanguageServer.jl as well.

**Comment by ZacLN** [comment]
https://github.com/ZacLN/DocumentFormat.jl
