### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by oxinabox** [ZacLN/CSTParser.jl#3]
I feel like Parser.jl is too generic.
Parser for what?

I suggest instead 

 - CstParser.jl
 - JuliaCstParser.jl

**Comment by ZacLN** [comment]
For sure, this was temporary. Is CST sufficiently understood as an acronym? My personal suggestion would be PirahaParser though that may be too high on the obscure axis and low on the amusing axis

**Comment by oxinabox** [comment]
CST on its own won't pass muster, wrt registration.

If you google CST Parser it gives good results
