### ISSUE TITLE
Incorrect parsing of '''

### ISSUE THREAD

**Issue by mauro3** [ZacLN/CSTParser.jl#37]
```
julia> '''
'\'': ASCII/Unicode U+0027 (category Po: Punctuation, other)
```
but it looks like it thinks is a multiline string.

**Comment by ZacLN** [comment]
This get's parsed as a `Char`
![screen](https://user-images.githubusercontent.com/5861046/29082529-49e0152e-7c55-11e7-811c-0adea6c11652.png)
?

**Comment by mauro3** [comment]
I get this:
![char](https://user-images.githubusercontent.com/4098145/29083074-c8ac1db4-7c67-11e7-8a25-ebc11064b131.png)
if I escape it (also valid), it works:
![char2](https://user-images.githubusercontent.com/4098145/29083087-d4ecfd5a-7c67-11e7-86bf-299ed011d33c.png)

**Comment by ZacLN** [comment]
Ah, this is the highlighter in `vscode` rather than the parser, I'll open an issue there
