### ISSUE TITLE
Keep more information in the CST

### ISSUE THREAD

**Issue by KristofferC** [ZacLN/CSTParser.jl#40]
I think it would be useful to keep more information in the CST e.g. comments and whitespace.
An example for another language (javascript) can be found at https://github.com/cst/cst.

In the image: 
![image](https://user-images.githubusercontent.com/1282691/29497792-e158f73e-85ee-11e7-90fc-ed74c8715365.png)

the ones with blue background are nodes and are important for syntax. The other ones (called tokens) are just whitespace or other trivia that can be deducible from the nodes. The job of a code-formatting would then be to write a CST -> string function and modify the tokens so that the string output looks nice.

**Comment by Keno** [comment]
Relevant slack transcript, to make it doesn't get lost: https://gist.github.com/Keno/60522c05004a374dd51043779ede9814

**Comment by KristofferC** [comment]
I think we can close this, since I am happy with the outcome of that discussion.

**Comment by ZacLN** [comment]
Yep I'm onboard with those thoughts. The scoping/linting interface in LanguageServer already works a bit like this, traversing the cst and creating a parallel tree
