### ISSUE TITLE
Expr_char v0.7 compatability

### ISSUE THREAD

**Issue by ZacLN** [ZacLN/CSTParser.jl#66]
@Keno , on v0.7
```
using CSTParser
c = String([0x, 0x, 0x])
s = "'$c'"
x = CSTParser.LITERAL(5, 1:5, s, CSTParser.Tokens.CHAR)
CSTParser.Expr_char(x)
```
gives
`ERROR: StringIndexError(....`
I don't know enough about strings/chars or changes made to them to fix this

**Comment by Keno** [comment]
That looks like there's literal zeros in the String. That's not really a legal character for a source file.
