### ISSUE TITLE
precompilation on 0.7 alpha seems stuck

### ISSUE THREAD

**Issue by kafisatz** [ZacLN/CSTParser.jl#69]
I am trying to use FemtoCleaner locally which requires CSTParser.

When 'using CSTParser', julia seems stuck on my computer (although the task manager in Windows10 shows the process is busy). 
Is this a compilation/precompilation regression on 0.7 alpha?
Is this working on other OS?

How long should I reasonably wait after 'using CSTParser'?

**Comment by ZacLN** [comment]
Hi, support for v0.7 is currently a work in progress ([branch](https://github.com/ZacLN/CSTParser.jl/pull/65) ), shouldn't be too long though

**Comment by kafisatz** [comment]
Thank you. I will keep track of that. Notably, also the CSTParser#v0.7compat branch takes ages to compile.

**Comment by ZacLN** [comment]
Yes it's unbearable, I'll have a look once everything is working

**Comment by Keno** [comment]
I've seen this as well. I was planning to look at this regression once the port to 0.7 is complete.

**Comment by davidanthoff** [comment]
I assume this is no longer an issue and we can close?

**Comment by kafisatz** [comment]
yes we can.
