### ISSUE TITLE
release to Julia 0.7/1.0 package system?

### ISSUE THREAD

**Issue by jingpengw** [ZacLN/CSTParser.jl#77]
It seems that the tests are good in Julia 0.7, the master branch could be registered as a new version for Julia 0.7?

**Comment by ZacLN** [comment]
Does it pass on j0.7? I don't have a build to check against, if so I'll drop the requirement for the v0.4 release

**Comment by jingpengw** [comment]
yep, it pass on 0.7. All the tests passed.

**Comment by jingpengw** [comment]
maybe you would like to merge the femtocleaner PR before releasing.
https://github.com/ZacLN/CSTParser.jl/pull/78
