### ISSUE TITLE
Formatting Utilities

### ISSUE THREAD

**Issue by MikeInnes** [ZacLN/CSTParser.jl#79]
For formatting purposes it's useful to extract certain formatting context information from a file; for example, the indenting style of the file as a whole (tabs/N spaces) or the indentation prefix of the current line. These things could live anywhere in principle (Deprecations.jl has its own set of layers over CSTParser, for example), but for the sake of making them more accessible and consistent, CSTParser seems like it'd be a good home for them.

If folks are on board I'll throw up a PR for some of these.

**Comment by ZacLN** [comment]
Hiya, my preference is to keep CSTParser as minimal as possible. Could these live [here](https://github.com/ZacLN/DocumentFormat.jl) which seems a good fit? Alternatively, I think @Keno was considering separating the CSTUtils subpackage from Deprecations

**Comment by MikeInnes** [comment]
Understandable. I'll close this for now then. When I have something I'll mention it here and we can decide how best to share all this stuff.
