### ISSUE TITLE
Triple strings aren't assigned Tokens.TRIPLE_STRING

### ISSUE THREAD

**Issue by domluna** [ZacLN/CSTParser.jl#88]
Consider

```julia
julia> x = CSTParser.parse("t = \"\"\"hello world\"\"\"")
BinarySyntaxOpCall  21 (21)
 ID: t  2 (1)
 OP: EQ  2 (1)
 LITERAL: hello world  17 (17)

julia> x.arg2.kind
STRING::Kind = 62
```

should be `TRIPLE_STRING::Kind = 63`.

Another thing to consider

```
julia> s0 = """
           txt = \"\"\"
           cannot document the following expression:

           \$(isa(ex, AbstractString) ? repr(ex) : ex)\"\"\"
       """
```

This will be parsed into a StringH type. Should the STRING literals inside be TRIPLE_STRING or would it make more sense to have a TripleStringH type?

**Comment by ZacLN** [comment]
fixed https://github.com/ZacLN/CSTParser.jl/commit/7370921ab8112b1091bacf750ca4603583744bed
