### ISSUE TITLE
parsing LITERAL removes newline

### ISSUE THREAD

**Issue by domluna** [ZacLN/CSTParser.jl#94]
```
julia> s
"\"\"\"\nInterpolate using `\\\$`\n\"\"\"\n"

julia> x = CSTParser.parse(s)
LITERAL: Interpolate using `$`
  31 (30)


julia> x.val
"Interpolate using `\$`\n"
```

should be ```"\nInterpolate using `\$`\n"```

**Comment by domluna** [comment]
another example https://github.com/domluna/JLFmt/issues/6

**Comment by ZacLN** [comment]
Initial newlines are dropped inside triple quotes:
```julia
julia> Meta.parse("\"\"\"\nInterpolate using `\\\$`\n\"\"\"\n")
"Interpolate using `\$`\n"
```

**Comment by domluna** [comment]
That's fine, we just need make sure the token kind is `TRIPLE_STRING` then. At the moment all token string Literals are assigned `STRING`.

I'm guessing the reason strings are unescaped is also to match `Meta.parse`?

**Comment by ZacLN** [comment]
fixed: https://github.com/ZacLN/CSTParser.jl/commit/7370921ab8112b1091bacf750ca4603583744bed
